language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t itayhasson12/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true itayhasson12/docker-react npm run test